[package]
name = "clicksnap"
version = "0.1.0"
edition = "2021"

[dependencies]
thirtyfour = "0.32.0-rc.5"
color-eyre = "0.6"
tokio = { version = "1.27", features = ["full"] }
async-trait = "0.1.60"
url = "2.3.1"
